label female_encounter:
  scene black with dissolve
  play sound "sounds/plane.ogg"
  $ renpy.pause(3.0, hard=True)
  girl "*Yawn*"
  "I stretch my arms and get up from my unbelievably uncomfortable chair, feeling way more refreshed after a short nap I just took."
  scene bg terminal with dissolve
  "Funny how an hour of sleep can revitalize you in the same way a full night's rest can!"
  "I should still have more than enough time before my flight, though perhaps I should check when it departs anyway..."
  "It's the first time I'm going to be on a plane, so it's better to be safe than sorry!"
  "Fully expecting to have at least an hour or two to kill, I casually stroll in the direction of the kiosk, noting the suspiciously late hour on the airport clock."
  "There are a lot of people all around me, checking their flights and speeding away after they do that, instantly replaced by more people wishing to use the kiosks."
  "Luckily, one of the kiosks has just gone vacant, and the older woman who was just using it smiling at me kindly as she walks away."
  "Alright, let's try to figure this out..."
  "I was never too good with electronics, but the kiosk's interface turns out to be very simple, so I start skimming through the countless lines of text, looking for my flight number."
  "I finally find it, so I focus on the row and prepare myself to see just how long I'll have to hang around before it arrives."
  "Let's see... Due in..."
  "Wait."
  "Why does it say \"Departed\"?"
  "Oh no... Oh no no no!"
  girl "Ugh, no!"
  "A frustrated shout escapes my lips, all of my past excitement disappearing and being replaced by hopelessness."
  girl "I can't believe it..."
  "Now I've really done it! I had everything planned, yet it somehow still didn't work out."
  "What am I even supposed to do now? My career is over before it even started... I fumbled the first and only chance I had!"
  "I need to do something! I need to do it now before I fully break down..."
  "I start looking around the place, and, through my eyes full of tears, I spot a man heading in my direction."
  "Perhaps he just wants to use the kiosk, so I take a few steps away from it to not bother him."
  "But no, he continues walking toward me."
  show guy frown with dissolve
  guyUnknown "Uh, hey... Did something happen?"
  "I can't help but stare at him shyly, perfectly understanding that he came all this way only because he saw me panicking rather badly."
  "My situation keeps becoming more embarrasing, it seems..."
  girl "Y-Yeah, it did... I missed my flight!"
  girl "I'm so stupid, I took a nap and slept way too long... Now I'm probably going to be stranded here!"
  guyUnknown smile "That's terrible... But it's not the end of the world!"
  girl "Maybe, but... I-I don't even know what I'm supposed to do now! It's my first flight ever, and of course, I just had to screw up like that."
  girl "I have no idea who to ask or-"
  "My voice breaks for a moment, the panic I'm trying to contain taking over my mind and not letting me think straight."
  "I'm going to burst into tears, right in front of this stranger..."
  guyUnknown "Look... It's really not as bad as it looks. How about we find an assistant that could give you a hand with getting you to your destination?"
  guyUnknown "I'm sure you can catch another plane."
  "An assistant...? And this man wants to help me find them?"
  "Maybe, if he were to accompany me... "
  "Also, it seems it's not his first time flying, and he knows exactly what to do when something doesn't go according to plan."
  "I take a second to catch my breath and look at the man, thankful for his assistance."
  girl "Y-You'd do that for me? *sniff* T-Thank you, I'd like that."
  "He smiles in response, and we start walking around the airport, weaving through droves of people as we look for anyone who could help me."
  "Though mostly it's him that's doing so, as I'm still shaken up by the whole ordeal, and the only thing I can concentrate on is following in his tow and making sure I don't shed any more tears."
  guyUnknown "Oh, look... I see an attendant over there!"
  guyUnknown "Excuse us! This lady here has a question for you."
  "The attendant quickly comes to us, putting on a kind, friendly smile as soon as she's close enough to hear us out."
  attendant "Yes? What seems to be the problem?"
  "The man looks in my direction, waiting for me to explain the dreadful situation that I'm in."
  "Gingerly, I open my mouth, not quite sure how to describe my problem."
  "This is so very embarrassing..."
  girl "W-Well, I was heading to Bristelline, and uh..."
  show guy frown with dissolve
  girl "I went to sleep and it got really late and then I was looking at the departure times and I... I didn't know what to do!"
  girl "I don't know if I should head home, or if I'll get my money back, or..."
  "I try my best, but it's pointless. I'm so anxious that I'm making no sense."
  "The attendant didn't understand a thing from what I just said. Not that I blame her..."
  "Instead, she looks at the man accompanying me."
  "I feel so bad... "
  "First, he has to deal with a sobbing, panicking girl while helping her out, and now, he'll also have to explain exactly what happened to her."
  guyUnknown smile "She basically took a nap and woke up too late to catch her flight. We want to put her on the next plane if that's not too much of a problem."
  attendant "Ahh... I see! That's awfully unfortunate, but I'm sure we can sort something out for you!"
  attendant "Bristelline is a very popular destination, so it shouldn't take long to find an empty seat on one of our many flights that are heading that way."
  "A wave of relief washes over me, finally calming me down and letting me think without feeling the terror taking control of my body."
  "I think... everything's going to be okay, after all."
  girl "Oh, thank you... That'd be a lifesaver!"
  guyUnknown "Well, it looks like you're in good hands! I told you it's not as bad as you thought."
  guyUnknown "Safe travels, and hope you'll enjoy your stay at Bristelline!"
  "My savior starts heading off the way he came, probably busy enough with his own matters."
  "I can't just let him go like that... I have to thank him, at the very least!"
  "So wanting to do just that, I gather all the courage I can muster and grab his shoulder, stopping him in his tracks."
  "Unhurriedly, he looks back at me with a curious expression on his face."
  show guy frown with dissolve
  girl "W-Wait... um, if I can ask you something..."
  girl "...What's your name?"
  guy smile "I'm [guyName]. And yours?"
  girl "I'm [girlName]. And I just wanted to say..."
  girl "Thank you, [guyName]... For caring enough to help a stranger out!"
  show guy frown with dissolve
  "He opens his mouth for a brief moment, as if he wanted to say something, but closes it soon after, opting to stare at me instead."
  "I get a bit flustered from this extended eye contact, his gentle eyes looking attentively at me, as if my simple thank you meant more than I thought it would to him..."
  "I don't even realize that I'm still holding his shoulder, lightly squeezing it with my fingers."
  "Maybe I made him feel uncomfortable..."
  "Or perhaps he's waiting for me to say something."
  attendant "Miss?"
  girl "Oh, sorry... I'll be right there!"
  show guy smile with dissolve
  "We exchange one last glance before I step away and join the attendant, leaving the conversation with [guyName] before it can progress."
  hide guy with dissolve
  "It's a shame... Even if it was too forward, I'd invite him to coffee to thank his efforts."
  "Though he probably has better things to do than sipping coffee with a stranger like me."
  return