label female_interlude:
  attendant "I've found an empty seat on a flight departing in 5 hours."
  attendant "Will that work for you?"
  girl "O-Of course! I'm just glad to be able to reschedule it without any extra costs."
  attendant "I'll go ahead and reserve that spot for you, then!"
  "She gets behind the company laptop, and after a minute of skillful pounding on the keyboard and a short trip to the employees-only area, she ultimately comes back with a brand new ticket for me."
  attendant "Here you go, miss. Make sure to not lose it!"
  attendant "You can learn more about the flight by checking it out in our kiosks."
  girl "I appreciate it so much! I can't begin to describe how thankful I am..."
  "We exchange our goodbyes and I start heading back to where I came from, tightly clutching the ticket."
  "The main area is slightly emptier than the last time, and the majority of kiosks are unoccupied and ready to use."
  "A bit more sure of what I'm doing now, I walk over and set my eyes on one of the kiosk's screens, searching for the flight number after looking it up on the boarding pass."
  "Just like the attendant said, it seems to be departing in around 5 hours."
  "Now I just have to make sure to not fall asleep for those next few hours..."
  "I don't think I can count on [guyName] helping me out again, even if I wouldn't mind seeing him one more time."
  "Although, he probably already boarded his plane and is on his way to whoever-knows-where."
  "I wonder why I'm still thinking of him..."
  "Maybe it's because he actually spent his time helping out a complete stranger, even accompanying me and helping me explain my situation to the airport staff."
  "The majority of people wouldn't bother with doing anything, a small number would stop and tell me to talk to the attendant, and maybe a handful of those would help with locating the attendant..."
  "But after that, they'd leave me on my own, something that [guyName] didn't do until he was completely sure I was in good hands."
  "He didn't even expect a reward or anything like that! All he wanted was to help a lost girl find her way to her destination."
  "If only I could thank him properly..."
  "But once again, pulling him away once more from whatever duties he has would be extremely rude of me."
  "I should've been able to solve the mistake I made from the very beginning."
  "Ah well, no use thinking about it anymore, I guess..."
  "I have several spare hours left, a time that wouldn't be spent best by moping around while hogging the kiosk to myself."
  "However, I also can't fall asleep again!"
  "I believe the next best thing for me would be to get some caffeine in my system."
  "That way, not only I'll prevent myself from dozing off but also I'll pass some of this free time that I have!"
  "Alright, then, that sounds like a plan! Let's hope I'll manage to find a cafe somewhere."
  return