label female_coffee:
  scene bg cafe with dissolve
  "Thankfully, the cafe wasn't as hard to locate as I thought it'd be, on account of all the advertisements for the local businesses strewn about the place, along with signs pointing potential customers in their direction."
  "Thanks to that, not ten minutes pass and I find myself in a cozy little airport cafe, sitting at one of the tables and sipping on hot coffee."
  "The prices might be a bit more overpriced than what I'm used to, but at least the coffee's really good!"
  "The place seems to be really popular, too, basically swarming with people, with them constantly coming and going."
  "With no one to talk to, I catch myself observing the different types of customers that frequent this shop."
  "Elderly couples, teenage girls, middle-aged men in business suits..."
  "It appears that everyone's thirsting for a nice cup of coffee, just like me!"
  "Some minutes pass and it feels as if I've seen people from all walks of life and no one can surprise me anymore."
  "Until I see someone familiar enter the cafe."
  "I'm not sure if it's him at first, only being able to see his back from where I'm sitting, but all my doubts disappear after he sits down and orders coffee, letting me catch a snippet of his voice."
  "It's [guyName]!"
  "I instinctively start getting up from my chair before I pause and sit down once more."
  "What if he doesn't feel like talking with me? Or..."
  "What if he's waiting for someone? Maybe a friend or a girlfriend..."
  "..."
  "I keep staring at him for way too long, debating with myself whether I should stand up and say hi to him, or if I should let him drink his coffee in peace."
  "This internal wrangle goes on until he turns around and looks straight at me, my eyes so focused on him that it ironically takes me a second to realize that he can see me."
  "Unlike me, he jumps into action pretty much instantly, rising from his chair and walking next to my table with a grin on his face."
  "I'm glad he took the first move, even if it was rather shameful, being caught staring at him like that..."
  show guy smile with dissolve
  guy "What a coincidence, us bumping into each other once again!"
  girl "Y-Yeah, tell me about it! I was almost sure that you took your plane and were on your way already."
  guy "I still have a few short hours before that... I imagine you do, too? Seeing as you're still here."
  girl "That's right. They managed to find a substitute flight for me, and I don't even have to wait until tomorrow!"
  girl "...Though it's not instant, either."
  girl "I have almost five hours until then. T-That's why I'm sitting here, in this coffee shop, wishing for the time to go by faster."
  guy "Well, maybe I could help you pass the time? It always goes quicker if you occupy yourself with a nice conversation!"
  girl "S-Sure thing! I can also use it as an opportunity to thank you for what you did earlier."
  "An idea dawns on me, one that will hurt my already-depleted funds, but one that [guyName] deserves."
  guy "Speaking of which... Do you like croissants?"
  guy grin "Is that even a question? I love them!"
  hide guy with dissolve
  "I let out a small chuckle and let him sit down as I walk over to the counter, where I order a sizable tray of steaming pastries."
  "They look delicious... perhaps they're worth the price, after all!"
  "Carrying the steaming tray, I come back to [guyName], who's now sitting comfortably and observing me with curiosity."
  girl "They came straight out of the oven, so they might be a bit hot!"
  show guy smile with dissolve
  guy "You know, I wasn't feeling hungry, but I don't think I'll be able to say no to those croissants!"
  girl "Ha-ha... Good! Eat as many as you want. It's my treat for having helped a damsel in distress!"
  return