label female_bonding:
  "As soon as I set them down on the table, he takes one and bites off a big chunk of it."
  guy grin "Mmm... Mmmm! Wow, it's really good."
  "I also grab one, and the smell of freshly baked goods making me very hungry."
  girl "Too bad we won't be able to enjoy them too often... Or do you perhaps take these kinds of flights on the regular?"
  guy smile "Not really, to be honest. I only visited this airport once in the past, when I was flying to Bristelline from my town."
  guy "Funnily enough, now I'm doing the same flight, just the other way around."
  girl "Huh, really? So, were you living in Bristelline?"
  guy "Yeah, for quite a few years. It's a nice place, but I wouldn't exactly call it home. That word can only belong to the town I grew up in."
  girl "You probably heard me tell the attendant about my flight, so you know I'm heading to Bristelline... "
  girl "What made you move there? Was it because of a g-girl?"
  "I involuntarily stutter at the last word, a bit embarrassed for not keeping my emotions in check."
  guy "No, it wasn't a girl. I got a very lucrative job offer from this one huge company, so I decided to take it and leave my previous life behind, pretty much."
  guy "Now I'm realizing that I'm missing my previous life, all my friends, my family..."
  guy "Sometimes I even catch myself daydreaming about eating a slice of apple pie from the diner down the street!"
  guy "I wonder if that place still exists..."
  guy "But enough about me. I don't want to bore you too much with my nostalgia! Why are you going to Bristelline, if I may ask?"
  girl "O-Oh, I actually really enjoyed hearing you talk about your town! It sounds so nice to live in..."
  guy "I can always bore you more later, then."
  girl "Of course! As for my reason for visiting the city... I guess it's kind of similar to yours, though not quite the same."
  "I take a deep breath, ready to explain something that I'm not fully sure about yet."
  girl "I'm {i}hoping{/i} to get a job there, but honestly, it might end up being a shot in the dark..."
  girl "As you can probably tell, I'm kind of out of my element here."
  girl "I-I really want the job, I'm not even too picky about what kind of role I'll get! I'll take anything at this point, as long as it lets me perfect my craft."
  guy frown "Hold on... You're hoping to land a role? So that means... that you're an actress?"
  girl "A-Aspiring actress, more like! But yes."
  "Upon hearing that, he looks shocked at me, definitely not expecting to hear something like that."
  "I want to laugh, but I stop myself for fear of appearing rude."
  "Seriously... It's really not that much of an achievement!"
  guy smile "That's amazing! Would this be your first role, or do you have some experience?"
  girl "I-I haven't starred in any movies if that's what you're asking about. But I starred in a couple of plays at my local theater."
  girl "Maybe it's not much to brag about, considering my town is probably even smaller than yours... But I always managed to pull in quite a crowd to watch our plays!"
  girl "Even had some people from the nearby city visit my town just to see me act."
  guy "You sound like quite a hit with the general public. I bet your acting is out of this world!"
  "He strokes my ego most pleasantly, my cheeks burning as a wave of embarrassment mixed with pride washes over my body."
  girl "It can be very stressful at times, especially having to remember all of the lines and mannerisms of the character you're supposed to play."
  girl "I'm always afraid of screwing up and stuttering during a line... or falling over and having the whole crowd laugh at me."
  guy frown "And did that ever happen?"
  "I look up, sifting through my memories in search of a situation like that, before I realize..."
  "All my screw-ups happened during recitals. So far, each one of my performances were flawless."
  girl "W-Well, no..."
  guy smile "You sound like a pretty proficient actress already. Plus, acting before a live crowd must be way more nerve-racking than doing it on set, don't you think?"
  guy "Following that train of thought, you're more than ready to act in front of a camera!"
  girl "Hmm..."
  "I haven't thought about it before, though what he's saying does make sense."
  "I'm always extremely afraid of doing something wrong during a performance, but nothing ever happens to me. Like I said, flawless every single time."
  "Not that there's never a chance for me to flop, though that chance is definitely much smaller than I thought."
  girl "You know, you raise some pretty good points!"
  girl "I'm not sure if it's as easy as you describe it, but... it probably must be at least easier than I thought."
  guy "Yeah! After all, you've already taken the hardest step in your career."
  guy "You took the initiative and now you're on your way to the capital of filmmaking. I've got to say, that's very impressive."
  girl "T-Thank you, [guyName]. It's nice to hear someone say that I did good and that I'm not setting myself up for disappointment."
  girl "God knows I heard the latter part way too many times from my parents' mouths..."
  guy frown "I take it they're not very supportive of your choice of career, right?"
  "I grimace, remembering that my last conversation with them was a loud and stressful argument."
  girl "T-That's putting it lightly... They really, really hate that I want to become an actress."
  girl "They think it's a waste of time and that instead, I should take care of the family business, just like my brothers."
  girl "They don't understand that I don't want to stack items and man the cash register in their store for the rest of my life."
  guy "I don't blame you. Excuse me for saying that, but it sounds like hell on earth."
  girl "You're absolutely right! It is. Not to mention dealing with customers... Retail is really the worst place to work in."
  "I shudder the memories of some of my most annoying customers flashing before my eyes."
  "Never again, no matter if I succeed in my acting job, or not!"
  girl "Acting is such a different world from what my parents want for me. You get to play out all those exciting scenarios..."
  girl "One month, you're an evil empress, quelling the protests in your kingdom with an iron hand..."
  girl "And the next, you're a scientist, trying to find a way to stop the onslaught of monsters from another universe."
  girl "I get to live through their thrilling lives without having to dedicate my whole to science or politics!"
  girl "Not to mention, I can still be myself off-screen. There are no negative consequences to any of the actions I do on the big screen, no matter how heinous they might be."
  girl "...Not that I fantasize about doing illegal or immoral things! I-I just meant t-that it's interesting to experience all of those things..."
  "For a moment I'm scared of it being taken the wrong way by [guyName], but he just laughs at it instead, and I can't help but join him."
  guy smile "Don't worry, I understand what you mean perfectly!"
  guy "I'm not going to lie, the way you describe it makes me want to try acting for myself!"
  guy "Though I'm probably going to pass and instead satiate my curiosity by watching your movie, as soon as you land a role in one, that is."
  girl "Ha-ha, that's a pretty optimistic way to see things! What if, instead of starring in a movie, I get cast for a toilet paper ad?"
  guy grin "Then I'm going to make some popcorn and put the ad on repeat until I fall asleep!"
  "We laugh up a storm, with no chance of stifling it until it dissipates naturally."
  "I feel really bad for the poor people around us! I wasn't trying to disturb their peace, but I just couldn't help myself..."
  guy smile "Honestly, I wasn't even joking! I'm going to watch anything that you act in because I know that you're going to do great no matter the role you're in."
  girl "Aren't you sweet..."
  "His eyes look at me with confidence, fully supportive of me, no matter what it is I'll end up doing."
  "I get lost in his face... until I realize what I'm doing and quickly avert my gaze."
  "To hide my embarrassment, I grab another pastry and bite into it, [guyName] joining me soon after."
  "We need a different topic... We can't just sit there in awkward silence!"
  "Perhaps... I'll ask him more about his plans. I feel like we've talked enough about me already."
  girl "You've told me a bit about you going back to your town and all that, but... What exactly are you planning to do after that?"
  guy "Honestly, I'm not exactly sure. I don't need to work for a while, so I can just take it easy for a year or two."
  guy "I might do all the things that piqued my interest, yet I never could find time to give them a shot."
  "A tiny pang of jealousy hits me as he says that."
  "It must be nice, not worrying about money..."
  "Though he undoubtedly earned it fair and square with hard work. I should be inspired by him and his self-reliance!"
  guy "I've always been curious about nature and how it'd be to explore it. I might do so and go into the forest trails near my town with a dirt bike!"
  guy "That sounds like something exciting I could enjoy."
  guy "It's about time I tried to broaden my horizons a bit."
  girl "Dirt biking? Isn't that kind of dangerous?"
  guy "It's not if you know what you're doing! Which I don't... but I'll learn."
  "I raise my eyebrows, feeling unsure about his potential new hobby."
  "It reminds me of this one video I saw a couple of years ago, with a very nasty motorbike crash."
  "The biker lost control of his machine and flew into a tree!"
  "His bike looked totally mangled, you couldn't discern the front from the back..."
  "What if something like that happens to [guyName]? Maybe he should look for a safer hobby, like modeling or metal detecting..."
  guy "Jokes aside, I'll be taking it easy until I know what I'm doing."
  guy "Low-speed, low-powered machines first! Not to mention that I'll always be wearing protective gear."
  girl "Still... What if you fall off your bike and break your neck? O-Or the engine dies on you and you get stranded!"
  "To my surprise, he leans forward and touches my hand."
  "I don't know how to react, apart from staring at him, mouth agape."
  "He's very gentle, his big, strong hand lightly stroking mine..."
  "Before I'm able to say something, he continues talking."
  guy "I'll be careful, I promise."
  guy "I know that it'd be much safer to just stay at home and continue doing what I know best, but then again... "
  guy "That's not really what you're doing either, right?"
  girl "H-Huh? Oh... you're right."
  girl "I suppose what I'm doing might be as risky as riding a dirt bike if not more..."
  guy "And does it bother you? It being risky?"
  girl "..."
  girl "Honestly, it kind of did before, but now I'm not sure..."
  guy "You might be braver than you think, then. You're willing to follow your dreams, no matter what other people say."
  "His hand freezes, slowly retracting... until I grab it, wrapping my fingers around his."
  "This time, he's the one who stares at me with bewilderment, blushing even harder than I did."
  "I'm not exactly sure what I'm doing either but... it feels right, somehow."
  "I just have to tell him something, anything, that would make us more than just a couple of strangers at an airport cafe."
  girl "[guyName], I..."
  girl "I know it might sound stupid because we met each other just a few hours ago..."
  "I feel the tension on his face, waiting for me to tell him what I mean."
  "His lip is quivering so he bites on it, stopping it from doing so."
  "He's as nervous as me, my heart beating so fast I'm afraid of it jumping out of my chest."
  girl "But I think you're a wonderful person, and I-I think I..."
  "Just as I'm about to ask the big question, a loud voice echoes through the corridors of the mall, produced by a loudspeaker just outside of the coffee shop."
  pa "Ladies and gentlemen, Flight 712 to Sunrise Ridge Airport is scheduled to depart shortly. All passengers are kindly requested to proceed to the boarding gate immediately."
  show guy frown with dissolve
  "I pause for a moment and let the announcement end before I continue."
  "They blare out periodically every couple of minutes, though this one is the most annoying by far."
  "Such bad timing..."
  pa "Please ensure you have your identification ready for a swift and efficient boarding process. We appreciate your prompt cooperation and we look forward to..."
  guy "Flight 712..."
  girl "Is there something wrong?"
  "He breathes in heavily, looking extremely upset."
  "It takes me a moment to realize what exactly did that announcement meant for him."
  girl "Don't tell me..."
  guy smile "Yeah, that's my flight."
  show guy frown with dissolve
  girl "..."
  "I notice his hand breaking its contact with mine, instantly leaving me with a longing to feel his touch again."
  "Why did it have to be now? Why couldn't we get at least five more minutes to enjoy each other's presence?"
  "I grip my coffee cup to calm myself, finding comfort in its warm texture. "
  guy "Well... I best be going then."
  guy "I probably don't have a lot of time until the plane departs."
  girl "Yeah... I guess we can't do anything about that, huh?"
  girl "No matter how much we might wish otherwise..."
  "He nods, and we both stand up, not knowing how to say goodbye to each other."
  "I wish he'd just hug me and tell me that he's going to cancel his flight, but I know that's an extremely selfish way of thinking."
  "At the very least, though... We don't have to say goodbye to each other right here, right now."
  "There is still plenty of time if you think about it!"
  "He turns around towards the exit, but, before he moves, I say something that makes a huge smile appear on his face once more."
  girl "So... You won't say no if I'll ask you to accompany you to your gate, right?"
  show guy smile with dissolve
  "I stick next to him and gently push him forward."
  "Ultimately, we exit the cafe and start heading to his gate despite my urge to do otherwise."
  return