label female_departure:
  scene bg terminal with dissolve
  show guy frown with dissolve
  "We maneuver our way through many occupied chairs, squeezing between people until we get to a pair of free seats, wasting no time and sitting on them before someone else does."
  "Judging by this crowd, it seems that we're one of the last people that arrived, some of the passengers already queuing up for the boarding process."
  "That means that our time is running short... though it's not over yet."
  girl "..."
  "I try to break the silence with a joke or something, though nothing comes to mind."
  "Silence hangs between us, interrupted only by people's quiet conversations and the sound of footsteps in the echoey hall."
  guy smile "Um... Do you maybe have a phone number I could notch down?"
  guy "I don't have my phone with me, but maybe when I come home, I could give you a call using the landline."
  guy "We could stay in contact... if that's what you'd want, of course."
  "His face lights up as he asks me his question, hoping that I have my phone number that I can share."
  "Sadly though, I'm about to douse his excitement."
  girl "I'm sorry... I never needed my own phone back in my little town."
  girl "It's stupid, isn't it? I'm heading to the big city, and the least I could bring with me would be some means of communication..."
  guy frown "Ah... I understand. Don't worry about it."
  "He slumps down in his chair, visibly disappointed."
  "I feel his pain. I should've invested in a phone before planning out this journey!"
  "How am I even supposed to respond to casting calls and job offers without one? I'm so shortsighted!"
  "And this shortsightedness might've just cost me a potential friend, or maybe even something more..."
  guy smile "So, about your big movie role... Are you thinking of playing a hero, or a villain?"
  "I look at him, surprised that he still wants to talk about my career."
  "Not that I mind, of course... I was just expecting that we'd spend those last moments together in silence."
  girl "You're really confident in me striking gold as soon as I land in Bristelline, huh?"
  guy grin "Of course! And I know I'm undoubtedly correct. You're going to leave all the competition in the dust!"
  guy "Mark my words! In a few months, I'm going to see your face plastered on all billboards."
  girl "You're silly! Besides, movies take {i}years{/i} to produce."
  guy "Oh, I haven't thought of that..."
  "We burst into laughter, maybe a little bit too loudly judging by the curious expressions of people around us."
  "I'm not sure if he's playing up how uninformed he is in that field, or does he really not know... Either way, he's successfully brightened up my mood."
  "He can be extremely silly at times... in a good way!"
  show guy smile with dissolve
  girl "Well, okay, okay! I'm going to be the next Mariloon Monotone, the Drama Queen herself, just because you say so! That much we know already."
  girl "What are you planning to do, though? Will you ever come back to Bristelline?"
  show guy frown with dissolve
  "He gazes at the ceiling as if he could find the answer to my question there."
  guy "I haven't thought that far in the future. I think I'm just going to follow my heart."
  guy smile "What's the use of having a plan if you're not sure you're going to stick to it, right?"
  "I nod slightly, agreeing with him."
  guy "So I might just stay in my town, perhaps even find something more interesting to do than pushing pencils."
  guy "Maybe I could open up a small hobby shop..."
  girl "A hobby shop, huh? That sounds pretty interesting!"
  girl "All the pleasures of owning a shop without the pain of stocking it up with fresh produce every day!"
  girl "Will you even get many customers, though? Having a specialty shop in a small town... N-Not that I'm saying the idea is bad!"
  "I change the tone of my sentence almost instantly, not wanting it to sound like I'm poking holes in his idea."
  "But thankfully, he just laughs, finding my question humorous."
  guy "God, I hope not! I'll be fine with just a few customers a week. It might not bring a lot of money, but I don't mind."
  guy "What matters to me the most is that I'll enjoy doing it and share my passion with like-minded people."
  girl "And what passion is that?"
  guy "I... I'm not sure yet."
  guy "Perhaps something to do with motorcycles. Maybe a spare parts shop? I could even do simple repairs on-site in the future."
  guy "I don't know anything about bikes yet, though I'm a quick and apt learner!"
  girl "If I'll ever ride a motorcycle, I'll make sure to visit your shop."
  "He tells me more about his idea for the future, both of us trying to ignore the empty seats becoming more common."
  "Most of the people are already inside the plane, with the rest standing in the boarding queue."
  "Soon, [guyName] will have to join them..."
  girl "..."
  show guy frown with dissolve
  "Is it right for us to go our separate ways, though?"
  "Maybe I could think of something to join him on his way back home! I could explain the situation to the ground staff, and maybe they'd take pity on me?"
  "I wouldn't be able to go to Bristelline as planned, though..."
  girl "I-I wonder if I could still cancel my flight..."
  "I say it quietly, but loud enough for [guyName] to hear."
  "I want him to tell me exactly how to do it, just like he did during rescheduling."
  "I want him to say that it's worth it, that we'll be able to stay together that way..."
  guy "Don't even think about it."
  "I glance at him in shock, unsure if I've heard him correctly."
  "Does he... not want to be with me?"
  guy smile "I don't want you missing your flight and potentially losing your chance at your dream job."
  guy "Let's follow our respective plans, okay? However shaky they might be, they're still our best chance at a happy future."
  show guy frown with dissolve
  "He looks away as if saying that pains him even more than me hearing it."
  "I want to protest and say that there's no happy future for me without him by my side, but I know deep down that what he's saying is the truth."
  "It's silly to think I could just cancel my flight and join his at the last possible moment. To throw away everything I've worked for just to have a chance with him."
  girl "I... Yeah, you're right."
  "We watch in silence as the line of travelers waiting to board decreases in size, the last few people who have been sitting standing up, leaving us alone in the waiting area."
  "And, all of them disappear inside the plane almost instantly, which means that only one person is left standing on the ground."
  "With a heavy heart, I urge him to stand up, before the plane leaves without him."
  "The staff gently hurries him up with polite gestures as well, the vehicle ready to take off."
  "He pauses before he does so, looking back at me."
  guy smile "I wanted to thank you for... everything."
  guy "It might sound exaggerated, but meeting you has brightened my future."
  guy "I wish we didn't have to end it here but, sadly, we don't have a choice."
  guy "I hope you'll have a good life and you'll achieve everything you set your mind to."
  guy "I'll be rooting for you, always."
  "He turns his back to me, as I hear a barely audible sniffling noise."
  "To my surprise, I'm the one producing it, not [guyName]."
  "On one hand, my heart hurts for having to let him go."
  "But on the other hand, I'm extremely happy for him to pursue his dreams, as happy as he is for me to do the same, undoubtedly."
  "Although... I can't just let him go like that, without showing him how much he means to me."
  show guy frown with dissolve
  "We become absorbed in each other's gaze."
  "For a moment, I don't know what to say, a sentiment he shares."
  "So, we let our bodies do all the talking."
  "We get closer together, bridging the gap between us, until..."
  scene cg kiss with Dissolve(2.0)
  "Our lips meet in a loving kiss."
  "It's so... natural for me."
  "As if we've been waiting to do this ever since we met each other."
  "We feel no embarrassment, awkwardness, or anything of the sort. Just pure, unfiltered passion."
  "He embraces me with his strong arms, hugging me tightly while our lips are glued together, exchanging heat."
  "It's so easy to get lost in this moment, to not want it to ever end..."
  "We could stay like that forever, and I don't think I would mind one bit."
  "So close to him, being able to pick up on the light smell of his perfume, his eyes staring at me so lovingly."
  "But unfortunately, all good moments must come to an end, no matter what."
  "We slowly break our kiss and distance our bodies, despite how much we long for each other."
  "I nod affirmatively at him as he glances at me one last time, before heading up the stairs and disappearing inside the interior of the aircraft."
  stop music fadeout 2.0
  play sound "sounds/plane.ogg"
  scene black with Dissolve(2.0)
  $ renpy.pause(3.0, hard=True)
  return