label female_ending:
  play music "sounds/Arrival.ogg" fadein 2.0
  scene bg radio with dissolve
  girl "...And that's the end of the story."
  girl "After that, I saw his face peeking through the window, our eyes met one last time before the plane started moving."
  girl "He looked... Happy. And I think I was happy, too."
  girl "It's... quite a story, isn't it?"
  dj "Y-Yeah... *Sniff* it is quite a story, alright..."
  dj "I can't believe it happened to you two! It's like something out of a movie, or a book..."
  dj "Wow, [girlName]. I don't even know what to say!"
  dj "Your emotive tale shook DJ Sonic Boom to his core! It really did!"
  girl "H-Haha, I'm... glad to hear that?"
  dj "Girl, I'm the one that's glad! I'm smiling, even though tears are running down my cheeks."
  dj "So, tell me... What do you think happened to [guyName] in the end?"
  dj "Do you think he opened up a hobby shop in his town?"
  dj "Or maybe he went back to work at his old company?"
  girl "Honestly... who knows?"
  girl "I'm only sure of one thing. Whatever he's doing now, he's pleased."
  girl "It's what he always wanted, and what he deserves."
  dj "I'm sure he is! I believe you helped him find happiness."
  girl "Y-You really think so?"
  dj "Yup! You guys basically compliment each other. You both helped each other in a different way... I'm sure our listeners agree with me!"
  girl "That just might be... Thanks to him, I found the courage to pursue my dreams and attend all the casting calls I could... And finally, it paid off."
  girl "I believe I owe a lot to him!"
  dj "Thank you once more for taking the time to tell us your beautiful story, [girlName]."
  girl "Thank you for letting me share it with the world!"
  dj "Now, before we say goodbye to each other... Do you think [guyName] is listening to you right now?"
  girl "I-I'm not sure... Personally, I doubt it. It's such a small chance for him to be tuned in at this exact moment!"
  dj "Aww, you never know! But okay, I know what you mean."
  dj "Though let's just pretend, okay? Imagine that he's tightly gripping his phone, in tears at hearing your voice once more..."
  girl "Ha-ha, okay... I can almost picture it!"
  dj "In that case... What would you say to him?"
  girl "Oh, gosh. I've got so many things that I want to share with him!"
  girl "[guyName], whatever you're doing right now, I'm certain that you achieved your goals."
  girl "I hope you still think about me from time to time, though not too much! I don't want you to have any regrets about us going our separate ways."
  girl "Even though it'll probably never happen... I do wish we could meet each other once more, and talk about our lives while eating croissants."
  girl "In a few weeks, I'll heading back to my town, to visit my parents and make peace with them."
  girl "I'm going to fly the same route as before, just in the opposite way."
  girl "Maybe we'll meet each other again, in yet another layover?"
  girl "I'm quite a sleepyhead..."
  girl "So if you spot a worried girl in front of a kiosk because her nap stretched a little too much, you know what to do!"
  $ achievement.grant("LUCIA_POV")
  scene black with Dissolve(2.0)
  return