label male_encounter:
  scene bg terminal with dissolve
  play sound "sounds/plane.ogg"
  $ renpy.pause(3.0, hard=True)
  "Alright, let's see how much time I have left until the next plane..."
  guy "Excuse me, excuse me..."
  "I make my way through crowds of clueless people, tense to not miss their flights."
  "Not that I blame them, I'm afraid of running late myself."
  "I scan the area for an unoccupied kiosk, which proves to be a bit more difficult than it sounds."
  "I'm used to flying regularly, though I never could get rid of the post-flight headaches I always get."
  "Wishing I could just sit down and catch my breath, I walk around until a big family stops hogging one of the screens, their flight sooner than they probably thought, judging by how quickly they left."
  "Finally free to check my own flight, I approach the screen and start skimming through all the information until I see the name of my hometown."
  "It seems like I have plenty of time until it's time to get on board. Way too much time, if you ask me."
  "Three whole hours... I guess I can always check my emails or-"
  "I pat my pockets, realizing I left my corporate smartphone in my office."
  "That's right, I never planned to take it with me, though old habits die hard, it seems."
  "Not knowing what else to do, I sit down on one of the nearby chairs and twiddle my thumbs for a moment."
  "It's probably good that I didn't take my phone with me... I know it's blowing up with the amount of calls it's receiving."
  "I clearly told everyone at work that I was going on a long break and to not contact me, no matter how important it was, though I doubt anyone actually followed my instructions."
  "Abandoning that stupid machine feels like a huge weight off my back. Now I can finally relax... Heck, I might even take a nap, why not?"
  "I grin to myself and close my eyes, trying to get comfortable on the stiff chair I'm sitting on."
  "The tension from my head slowly disappears, replaced with a warm sensation. My consciousness begins to drift away, the world around me becoming hazy..."
  girlUnknown "Ugh, no!"
  girlUnknown "I can't believe it..."
  "...That is until a loud, upset voice brings me back to reality."
  "Curious to see who's making such a racket, I open my eyes and look around, identifying the source at one of the kiosks nearby."
  show girl frown with dissolve
  "A girl, around my age, or maybe a bit younger, her shoulders slumped and her face partially hidden behind her hands."
  "She's obviously very upset, maybe even in distress, looking around the whole place as if she was searching for something... or someone."
  "I feel a bit bad for her, whatever it is that happened to her, so I decide to approach her and see what it is that made her so anxious."
  guy "Uh, hey... Did something happen?"
  girlUnknown "Y-Yeah, it did... I missed my flight!"
  girlUnknown "I'm so stupid, I took a nap and slept way too long... Now I'm probably going to be stranded here!"
  "She's on the verge of tears, her hands tightly clenched into fists."
  guy "That's terrible... But it's not the end of the world!"
  girlUnknown "Maybe, but... I-I don't even know what I'm supposed to do now! It's my first flight ever, and of course, I just had to screw up like that."
  girlUnknown "I have no idea who to ask or-"
  "Her voice trails off, a tear escaping past her eyelid and slowly running down her cheek."
  "She's panicking badly... I can't leave her alone when she's like that. I've got to help her out!"
  guy "Look... It's really not as bad as it looks. How about we find an assistant that could give you a hand with getting you to your destination?"
  guy "I'm sure you can catch another plane."
  girlUnknown "Y-You'd do that for me? *sniff* T-Thank you, I'd like that."
  "I send a reassuring smile her way as we start looking for the attendant, my companion sneakily drying off her tears with a handkerchief she produced."
  "I feel sorry for her since it must be pretty stressful to miss your first-ever flight."
  "But on the other hand, she should've been way more cautious. Falling asleep without setting up an alarm is a risky gamble! One that she lost and now she has to face the consequences."
  "I can't see that happening to me. The idea alone of arriving late to any sort of appointment is appalling..."
  "Even still, it's not in my position to judge."
  "What if she's visiting an ill relative? Or maybe she's flying to attend a funeral... I literally have no idea what's currently happening in her life."
  "Admittedly, a stressful situation on top of an unplanned disruption of your plans would make anyone lose their head."
  guy "Oh, look... I see an attendant over there!"
  guy "Excuse us! This lady here has a question for you."
  "The attendant quickly makes her way towards us, putting on a kind, friendly smile as soon as she's close enough to hear us out."
  attendant "Yes? What seems to be the problem?"
  "The girl who lost her flight goes wide-eyed, stammering for words as she's trying to describe what happened... with poor results."
  girlUnknown "W-Well, I was heading to Bristelline, and uh... "
  girlUnknown "I went to sleep and it got really late and then I was looking at the departure times and I... I didn't know what to do!"
  girlUnknown "I don't know if I should head home, or if I'll I get my money back, or..."
  "The attendant tries to follow her messy train of thought, expressed way too fast with a shaky voice, though in the end, she fails and glances in my direction, hoping I could translate what the girl just said."
  guy "She basically took a nap and woke up too late to catch her flight. We want to put her on the next plane if that's not too much of a problem."
  attendant "Ahh... I see! That's awfully unfortunate, but I'm sure we can sort something out for you!"
  attendant "Bristelline is a very popular destination, so it shouldn't take long to find an empty seat on one of our many flights that are heading that way."
  girlUnknown sorry "Oh, thank you... That'd be a lifesaver!"
  guy "Well, it looks like you're in good hands! I told you it's not as bad as you thought."
  guy "Safe travels, and hope you'll enjoy your stay at Bristelline!"
  "I start heading off back to my previous spot, knowing that the friendly assistant will surely sort out all of her problems."
  "That is until I feel a hand grabbing my shoulder."
  girlUnknown curious "W-Wait... um, if I can ask you something..."
  girlUnknown "...What's your name?"
  guy "I'm [guyName]. And yours?"
  girl sorry "I'm [girlName]. And I just wanted to say..."
  girl "Thank you, [guyName]... For caring enough to help a stranger out!"
  "She looks me in the eye with indebtedness, her cheeks lightly blushing and her hand gently squeezing my shoulder."
  "I can't help but start to get lost in those big eyes, now happy and free of tears..."
  attendant "Miss?"
  girl curious "Oh, sorry... I'll be right there!"
  "We exchange one last glance before she steps away and joins the attendant, leaving me alone and with an odd, warm sensation, which the meaning of I can't quite decipher."
  return