label male_interlude:
  scene black with dissolve
  "Having nothing else to do for now, and not feeling like taking a nap anymore, I go where my legs take me, which turns out to be a duty-free mall."
  scene bg shopping with dissolve
  "Maybe I'll find something small I could take with me and gift to my parents back home."
  "I'm kind of embarrassed I haven't thought about getting something for them before, despite them always saying that the biggest gift I could get them would be visiting them more often."
  "It might be a bit corny, but, I know where they're coming from... "
  "I haven't done a good job of keeping in contact with them and the rest of my family."
  "Same for my friends that I left in my town... I barely spoke with them in the last few years."
  "I sure hope they'll still want to hang out with me when I come back."
  "I roam around the mall, going from aisle to aisle and checking out all the different items they have on sale."
  "Most of them are way too expensive for what they are, not that money's much of a problem for me."
  "Though I refuse to spend it on something that'd end up in the trash anyway."
  "A bit disappointed, I move over to the food section, despite not being very hungry."
  "I wonder what that fidgety girl, [girlName], is doing now..."
  "Maybe she's already on another plane, heading to Bristelline, just like she wanted."
  "It's funny... I didn't mention to her that I just flew back from there."
  "Not that it matters, I suppose."
  "Even though I only knew her for a few moments, she seemed like a sweet girl. A bit too shy for her own good, maybe."
  "In the company I used to work for, she wouldn't have lasted a month. She lacks determination and assertiveness apart from foresight and reliability."
  "She must start prioritizing properly or else this incident will repeat itself in the future."
  "I hope she learned a valuable lesson today. Indeed, there are many things she has to change, but being always early to save her countless troubles will be a good start."
  "That worked for me, so I'm sure it'll work for her, too."
  "..."
  "Why am I still thinking about her?"
  "I simply provided her with a bit of assistance, and that's about it."
  "We're both strangers to each other."
  "Well, I guess we're not complete strangers, seeing that we know each other's names..."
  "I grab a pack of mints along with a bottle of water and I head to the cash register, promptly paying for my tiny shopping with my card."
  "I wasted a bit of time, wandering around the mall while wrapped up in thought, though I still have around two hours."
  "What to do, what to do..."
  "Hmm, a hot cup of coffee sounds pretty nice right now, and I can bet my life savings that there's definitely a good coffee shop around here somewhere!"
  "With a new goal in my mind, I stow the bottle and hard candy in my pouch and walk out of the supermarket and into the mall corridor."
  "It takes me just a minute to spot a huge banner, advertising a cafe located a couple steps away from where I'm standing."
  "Excited to finally receive my daily dose of caffeine, I step inside, the interior turning out to be quite cozy and inviting."
  return