label male_bonding:
  show girl smile with dissolve
  "I grab one of the croissants, its crust warm and crunchy before I drive it to my mouth and take a big bite."
  guy "Mmm... Mmmm! Wow, it's really good."
  "Curious to see if I'm playing up my enthusiasm or not, she follows suit, breaking the pastry in half and eating the smaller one."
  girl "Hmm... Yeah! So simple, yet so sweet and delicious..."
  girl "Too bad we won't be able to enjoy them too often... Or do you perhaps take these kinds of flights on the regular?"
  guy "Not really, to be honest. I only visited this airport once in the past, when I was flying to Bristelline from my town."
  guy "Funnily enough, now I'm doing the same flight, just the other way around."
  girl curious "Huh, really? So, were you living in Bristelline?"
  guy "Yeah, for quite a few years. It's a nice place, but I wouldn't exactly call it home. That word can only belong to the town I grew up in."
  girl smile "You probably heard me tell the attendant about my flight, so you know I'm heading to Bristelline..."
  girl sorry "What made you move there? Was it because of a g-girl?"
  "[girlName] stutters while saying that, her face reflecting a hint of envy, which goes away as quickly as it appeared."
  guy "No, it wasn't a girl. I got a very lucrative job offer from this one huge company, so I decided to take it and leave my previous life behind, pretty much."
  show girl smile with dissolve
  guy "Now I'm realizing that I'm missing my previous life, all my friends, my family... "
  guy "Sometimes I even catch myself daydreaming about eating a slice of apple pie from the diner down the street!"
  guy "I wonder if that place still exists..."
  "I crack a smile, feeling a bit awkward for derailing the topic so much."
  guy "But enough about me. I don't want to bore you too much with my nostalgia! Why are you going to Bristelline, if I may ask?"
  girl blush "O-Oh, I actually really enjoyed hearing you talk about your town! It sounds so nice to live in..."
  guy "I can always bore you more later, then."
  girl grin "Of course! As for my reason for visiting the city... I guess it's kind of similar to yours, though not quite the same."
  girl sorry "I'm {i}hoping{/i} to get a job there, but honestly, it might end up being a shot in the dark..."
  girl "As you can probably tell, I'm kind of out of my element here."
  girl "I-I really want the job, I'm not even too picky about what kind of role I'll get! I'll take anything at this point, as long as it lets me perfect my craft."
  "Part of what she says intrigues me a lot, so I decide to ask her a quick question."
  guy "Hold on... You're hoping to land a role? So that means... that you're an actress?"
  girl "A-Aspiring actress, more like! But yes."
  "I widen my eyes, impressed to hear how someone as bashful as [girlName] is pursuing her dreams so brashly."
  "Taking a flight to a completely new city, without formulating an extensive plan on top of not having at least five backup plans in case things don't work out?"
  "I don't think I'd be able to do that... Though I can't say that I dislike her approach to life."
  "If I've learned something from my stay in the corporate world is that living bound by an aggressive schedule isn't definitely the best."
  "Huh, perhaps that's what I need... Some whimsy and spontaneity in my life."
  guy "That's amazing! Would this be your first role, or do you have some experience?"
  girl "I-I haven't starred in any movies if that's what you're asking about. But I starred in a couple of plays at my local theater."
  girl "Maybe it's not much to brag about, considering my town is probably even smaller than yours... But I always managed to pull in quite a crowd to watch our plays!"
  girl "Even had some people from the nearby city visit my town just to see me act."
  guy "You sound like quite a hit with the general public. I bet your acting is out of this world!"
  show girl blush with dissolve
  "She blushes at my compliment, gently shaking her head."
  "From what I'm hearing, she appears to be someone completely different on stage."
  "If she was more like that in real life, things would go wonderfully to her!"
  girl "Ha-ha, I don't know... Honestly, it's still something that I don't feel fully comfortable in."
  girl sorry "It can be very stressful at times, especially having to remember all of the lines and mannerisms of the character you're supposed to play."
  girl "I'm always afraid of screwing up and stuttering during a line... or falling over and having the whole crowd laugh at me."
  guy "And did that ever happen?"
  girl neutral "W-Well, no..."
  show girl sorry with dissolve
  "A slight smile appears on her face when she realizes that."
  "Everyone experiences stage fright, but not a lot of people can contain it like her. That's where her talent kicks in."
  guy "You sound like a pretty proficient actress already. Plus, acting before a live crowd must be way more nerve-racking than doing it on set, don't you think?"
  guy "Following that train of thought, you're more than ready to act in front of a camera!"
  girl neutral "Hmm..."
  "She tilts her head slightly, deep in thought."
  "I can't say I know much about being an actor, but that's exactly how I feel."
  "Doing something live sounds way more serious than being able to retake the same scene as many times as needed."
  girl smile "You know, you raise some pretty good points!"
  girl "I'm not sure if it's as easy as you describe it, but... it probably must be at least easier than I thought."
  guy "Yeah! After all, you've already taken the hardest step in your career."
  guy "You took the initiative and now you're on your way to the capital of filmmaking. I've got to say, that's very impressive."
  show girl blush with dissolve
  "Her cheeks adopt a red hue as she giggles shyly, trying to hide her face by sipping from her cup of coffee."
  girl "T-Thank you, [guyName]. It's nice to hear someone say that I did good and that I'm not setting myself up for disappointment."
  girl sorry "God knows I heard the latter part way too many times from my parents' mouths..."
  guy "I take it they're not very supportive of your choice of career, right?"
  girl "T-That's putting it lightly... They really, really hate that I want to become an actress."
  girl frown "They think it's a waste of time and that instead, I should take care of the family business, just like my brothers."
  girl "They don't understand that I don't want to stack items and man the cash register in their store for the rest of my life."
  guy "I don't blame you. Excuse me for saying that, but it sounds like hell on earth."
  girl sorry "You're absolutely right! It is. Not to mention dealing with customers... Retail is really the worst place to work in."
  "Can't say I've ever had such restrictive parents as her, rather, mine were always supportive of whatever it is I wanted to do."
  "I feel sorry for her... It must be terrible, having someone so close to you always trying to bring you down and wanting to dictate your whole life."
  girl smile "Acting is such a different world from what my parents want for me. You get to play out all those exciting scenarios..."
  girl "One month, you're an evil empress, quelling the protests in your kingdom with an iron hand..."
  girl "And the next, you're a scientist, trying to find a way to stop the onslaught of monsters from another universe."
  girl blush "I get to live through their thrilling lives without having to dedicate my whole to science or politics!"
  girl "Not to mention, I can still be myself off-screen. There are no negative consequences to any of the actions I do on the big screen, no matter how heinous they might be."
  girl sorry "...Not that I fantasize about doing illegal or immoral things! I-I just meant t-that it's interesting to experience all of those things..."
  "I can't resist giggling at that, her conflicted expression turning into a wide grin as she joins me."
  guy "Don't worry, I understand what you mean perfectly!"
  guy "I'm not going to lie, the way you describe it makes me want to try acting for myself!"
  guy "Though I'm probably going to pass and instead satiate my curiosity by watching your movie, as soon as you land a role in one, that is."
  girl grin "Ha-ha, that's a pretty optimistic way to see things! What if, instead of starring in a movie, I get cast for a toilet paper ad?"
  guy "Then I'm going to make some popcorn and put the ad on repeat until I fall asleep!"
  "This time, we both erupt with laughter, [girlName] trying to suppress it by hiding her face in her hands, which makes me cackle even louder."
  "Finally, our laughter peters out, the rest of the patrons in the cafe staring at us with curious, but amused faces."
  "I feel a bit embarrassed but I decide to not worry about it too much and instead ignore everyone except for [girlName]."
  "I have to admit, only paying heed to the things and the people you like is liberating."
  guy "Honestly, I wasn't even joking! I'm going to watch anything that you act in because I know that you're going to do great no matter the role you're in."
  girl smile "Aren't you sweet..."
  "We both stare into each other's eyes for a short while, until [girlName] turns her head with a sheepish smile, grabbing a pastry and taking a small bite."
  "I do the same, and we start eating our sweet treats in silence, not knowing what to say next."
  "I can't help but notice that my heart is beating much faster than it was at the beginning of this conversation..."
  girl "You've told me a bit about you going back to your town and all that, but... What exactly are you planning to do after that?"
  guy "Honestly, I'm not exactly sure. I don't need to work for a while, so I can just take it easy for a year or two."
  guy "I might do all the things that piqued my interest, yet I never could find time to give them a shot."
  guy "I've always been curious about nature and how it'd be to explore it. I might do so and go into the forest trails near my town with a dirt bike!"
  guy "That sounds like something exciting I could enjoy."
  guy "Apart from that... I'll just try to enjoy a little bit of everything. I won't say no to any kind of activity that I stumble upon."
  guy "It's about time I tried to broaden my horizons a bit."
  girl neutral "Dirt biking? Isn't that kind of dangerous?"
  guy "It's not if you know what you're doing! Which I don't... but I'll learn."
  "[girlName] raises her eyebrows in response, shocked to hear that I'm interested in something she deems as life-threatening."
  "Ironically, I'm willing to do these things because that's exactly what she's doing."
  "Going all out, and living to the fullest, are two things I've prevented myself from fulfilling for long enough."
  "And if [girlName] can do it, why couldn't I? "
  guy "Jokes aside, I'll be taking it easy until I know what I'm doing. "
  guy "Low-speed, low-powered machines first! Not to mention that I'll always be wearing protective gear."
  girl frown "Still... What if you fall off your bike and break your neck? O-Or the engine dies on you and you get stranded!"
  "Instinctively, I lean closer to her and gently touch her hand, resting on the table."
  show girl curious with dissolve
  "Her skin is soft and warm, her petite fingers quivering slightly at this sudden sensation."
  guy "I'll be careful, I promise."
  guy "I know that it'd be much safer to just stay at home and continue doing what I know best, but then again... "
  guy "That's not really what you're doing either, right?"
  girl neutral "H-Huh? Oh... you're right."
  girl "I suppose what I'm doing might be as risky as riding a dirt bike if not more..."
  guy "And does it bother you? It being risky?"
  girl "..."
  girl "Honestly, it kind of did before, but now I'm not sure..."
  guy "You might be braver than you think, then. You're willing to follow your dreams, no matter what other people say."
  "Her hand starts moving, and, just when I think she's going to take it away, just when I think I went too far..."
  show girl smile with dissolve
  "She reciprocates my touch by tightly grabbing my hand and wrapping her fingers around mine."
  "My heart nearly jumps out of my chest, beating like a hummingbird."
  "However, it manages to increase its tempo even more when [girlName]'s face glows with affection, her pretty eyes staring at me with such warmth, that it's hard to put it into words."
  girl sorry "[guyName], I..."
  girl "I know it might sound stupid because we met each other just a few hours ago..."
  "I bite my lip nervously, struggling to keep my cool."
  "The anticipation is killing me, but I try to control my breathing and wait patiently. It wouldn't be wise to rush her when she's as tense as me, if not more."
  girl "But I think you're a wonderful person, and I-I think I..."
  "Just as she's about to finish her sentence, a formal voice booms out from the nearby loudspeaker, just outside the cafe's doors."
  pa "Ladies and gentlemen, Flight 712 to Sunrise Ridge Airport is scheduled to depart shortly. All passengers are kindly requested to proceed to the boarding gate immediately."
  show girl neutral with dissolve
  pa "Please ensure you have your identification ready for a swift and efficient boarding process. We appreciate your prompt cooperation and we look forward to..."
  guy "Flight 712..."
  girl "Is there something wrong?"
  "All color drains from her face as she realizes what this announcement just meant for me."
  girl "Don't tell me..."
  guy "Yeah, that's my flight."
  girl frown "..."
  "We slowly break our contact, our hands drifting apart as this romantic setting turns into something much more depressing."
  "Argh, did all my free time really pass by so quickly? How is that possible?"
  "I glance at [girlName], holding a brave, understanding smile as her hands grip the still-hot coffee cup, its temperature seemingly unnoticed by her."
  guy "Well... I best be going then."
  guy "I probably don't have a lot of time until the plane departs."
  girl sorry "Yeah... I guess we can't do anything about that, huh?"
  girl "No matter how much we might wish otherwise..."
  "I nod, the inside of my mouth suddenly feeling as dry and coarse as sandpaper."
  "We both stand up, struggling to keep our composure."
  "I want to hug her so much, but... I don't know if it's the right thing to do at the moment."
  girl "So... You won't say no if I'll ask you to accompany you to your gate, right?"
  "A warm, gratuitous smile spreads across my face as [girlName] sticks to my side, her hand pushing me gently so that I don't stop."
  "We exit the coffee shop and start heading towards the gate, her presence providing the encouragement I need to propel my steps forward."
  return