label male_departure:
  scene bg terminal with dissolve
  show girl frown with dissolve
  "Arriving near the gate, we sit down on one of the empty seats, their scarcity showcasing that we're one of the last people to arrive."
  "The boarding process is just starting, which means that we should at least have a few minutes left."
  "Enough to say goodbye."
  girl "..."
  "I look over at [girlName], hoping that she'll say something, something that could make peace with the whole situation."
  "Sadly, she's as lost as me, the lump in my throat the size of a ping-pong ball preventing me from speaking."
  "There are so many things I want to say to her, and at the same time, I'm at such a loss for words..."
  "I have just one idea left before I accept that those are our last moments together."
  show girl neutral with dissolve
  guy "Um... Do you maybe have a phone number I could notch down?"
  guy "I don't have my phone with me, but maybe when I come home, I could give you a call using the landline."
  guy "We could stay in contact... if that's what you'd want, of course."
  girl sorry "I'm sorry... I never needed my phone back in my little town."
  girl "It's stupid, isn't it? I'm heading to the big city, and the least I could bring with me would be some means of communication..."
  guy "Ah... I understand. Don't worry about it."
  "And just like that, my last, desperate attempt at preserving our connection meets its abrupt end."
  "The only thing I can do now is make our closing moments together worthwhile."
  "We don't have to separate on a somber note. Let's make it a happy memory instead!"
  guy "So, about your big movie role... Are you thinking of playing a hero, or a villain?"
  show girl neutral with dissolve
  "She looks at me, a bit confused at the sudden change of topic, before she snickers and shakes her head."
  girl grin "You're really confident in me striking gold as soon as I land in Bristelline, huh?"
  guy "Of course! And I know I'm undoubtedly correct. You're going to leave all the competition in the dust!"
  guy "Mark my words! In a few months, I'm going to see your face plastered on all billboards."
  girl "You're silly! Besides, movies take {i}years{/i} to produce."
  guy "Oh, I haven't thought of that..."
  "We share a hearty chuckle, our previous gloomy faces now brightened with fresh smiles."
  girl blush "Well, okay, okay! I'm going to be the next Mariloon Monotone, the Drama Queen herself, just because you say so! That much we know already."
  girl smile "What are you planning to do, though? Will you ever come back to Bristelline?"
  guy "I haven't thought that far in the future. I think I'm just going to follow my heart."
  guy "What's the use of having a plan if you're not sure you're going to stick to it, right?"
  guy "So I might just stay in my town, perhaps even find something more interesting to do than pushing pencils."
  guy "Maybe I could open up a small hobby shop..."
  "I blink rapidly, slightly surprised at what I'm saying."
  "I thought I was going to spend a year or two in my town and go back to the city refreshed, yet it seems like a new idea just sprung to my mind."
  "And it's an idea that sounds way more compelling than the previous one."
  "I don't want to run away from the corporate world only to return some time later... I want to stay away from it forever."
  girl "A hobby shop, huh? That sounds pretty interesting!"
  girl "All the pleasures of owning a shop without the pain of stocking it up with fresh produce every day!"
  girl sorry "Will you even get many customers, though? Having a specialty shop in a small town... N-Not that I'm saying the idea is bad!"
  guy "God, I hope not! I'll be fine with just a few customers a week. It might not bring a lot of money, but I don't mind."
  guy "What matters to me the most is that I'll enjoy doing it and share my passion with like-minded people."
  girl neutral "And what passion is that?"
  guy "I... I'm not sure yet."
  guy "Perhaps something to do with motorcycles. Maybe a spare parts shop? I could even do simple repairs on-site in the future."
  guy "I don't know anything about bikes yet, though I'm a quick and apt learner!"
  girl grin "If I'll ever ride a motorcycle, I'll make sure to visit your shop."
  show girl smile with dissolve
  "We both get lost in the conversation, oblivious to the amount of people occupying the chairs in the waiting area getting smaller and smaller, until we're one of the last people remaining."
  "The rest is already queuing up for the boarding, with a good amount of people already inside the plane."
  "Our time together is slowly ticking away..."
  girl frown "..."
  girl "I-I wonder if I could still cancel my flight..."
  "[girlName]'s stray comment sways me, her idea so tempting that I contemplate losing my flight so that I could spend more time with her."
  "However, as much as it pains us, we cannot do that to ourselves, not after everything we've done to get where we are."
  guy "Don't even think about it."
  show girl neutral with dissolve
  "A bit startled at my serious tone, she looks at me, bewildered."
  guy "I don't want you missing your flight and potentially losing your chance at your dream job."
  guy "Let's follow our respective plans, okay? However shaky they might be, they're still our best chance at a happy future."
  "\"Even if I'd prefer to throw everything away and join you instead\" is what I want to add, though I refrain from doing so."
  "She doesn't need anyone to play with her feelings like that. This situation is already hard for both of us as is."
  girl sorry "I... Yeah, you're right."
  "The line reduces its length at a speedy pace, more people gradually disappearing inside the metallic bird that'll fly me to my destination."
  "Finally, I'm the last person still on the ground, the boarding staff politely gesturing me to hurry up and get on the plane."
  "I close my eyes for a moment and take a deep breath, turning away from the plane to look at [girlName] one last time."
  guy "I wanted to thank you for... everything."
  show girl neutral with dissolve
  guy "It might sound exaggerated, but meeting you has brightened my future."
  guy "I wish we didn't have to end it here but, sadly, we don't have a choice."
  guy "I hope you'll have a good life and you'll achieve everything you set your mind to."
  guy "I'll be rooting for you, always."
  "Aware that my composure is at its limit and I'm on the verge of tears, I quickly turn back and start heading to the stairs, hoping to escape before that happens."
  "But as I'm retreating, I feel her hand on my shoulder, strongly clutching it and prompting me to look back at her."
  show girl sorry with dissolve
  "Her eyes stare at me longingly, her lips quivering, unable to say anything."
  "I try to comfort her, but I don't know how, so we end up looking at each other, in silence."
  "The whole world seems to fade away, all the voices, sounds, people..."
  "All of them vanish until the only thing I can see is her, and the only sounds I can hear are her breathing and our heartbeats, beating strongly in unison."
  "Before I know it, we instinctively start leaning towards each other, our lips drawing nearer, until..."
  scene cg kiss with Dissolve(2.0)
  "They finally meet."
  "She tastes so sweet... Her soft lips pulling me in and not wanting to let go."
  "I close my eyes reflexively, but I soon open them, wanting to see her beautiful face for as long as I can."
  "Her flushed cheeks, her soft hair gently tickling my skin, her long, dark eyelashes, her glowing eyes, radiating love and kindness..."
  "I embrace her further in a tight hug, scared that she'll drift away if I release her for even a moment."
  "We stay like that for what seems like an eternity, yet it still feels too short for me."
  "Finally, though, we have to break away our kiss, and slowly distance our bodies."
  "I take one last look at her smiling face, and, delighted, I walk up the stairs and board the plane."
  stop music fadeout 2.0
  play sound "sounds/plane.ogg"
  scene black with Dissolve(2.0)
  $ renpy.pause(3.0, hard=True)
  return