label male_ending:
  play music "sounds/Arrival.ogg" fadein 2.0
  scene bg radio with dissolve
  guy "...And yeah, that's what happened."
  guy "The door closed, I sat down in my seat, and I managed to catch one last glimpse of her face through the plane window before we started moving."
  guy "It's the last time I saw her."
  guy "..."
  guy "Uh... Am I still on the line?"
  guy "Did the call cut off? Hello? DJ Sonic Boom?"
  dj "Ahem... *Sniff* Y-Yeah, you're alright [guyName]! We're hearing you loud and clear."
  dj "Sorry, I just... Whew, that's quite a moving story, isn't it?"
  dj "Two lost souls, meeting each other at an airport and finding a new meaning in their respective lives..."
  dj "I'm going to be honest with you, [guyName]... You made a grown man cry! And I'm not ashamed to say it."
  guy "Ha-ha, well, I'm sorry for that. I didn't mean for it to turn into a sob story."
  guy "In fact, I believe it's happier than sad. I'm cherishing that encounter every single day."
  dj "So you still think about her daily, huh? Do you... love her?"
  guy "...I'm not sure if I should say that on such a huge broadcast."
  guy "I think it's one of those things that you say in private, face-to-face with that other person."
  dj "You're absolutely right, excuse my pushiness..."
  dj "Do you think [girlName] became a movie star, just like she wanted?"
  guy "I'm sure of it. Whoever hired her did a great job because I know what she's capable of. One day, sooner than later, she's going to be huge."
  dj "Maybe we'll hear of her in a couple of months, right? Just don't get too jealous if she'll have to kiss another man in the movie! Heh, heh..."
  dj "Jokes aside, I can't help but root for her, too! And I'm sure our listeners do as well."
  dj "[guyName], thank you very much for calling us and taking the time to share this beautiful story with us!"
  guy "It was my pleasure."
  dj "And before you disconnect... Do you think [girlName] is listening to us right now?"
  guy "Honestly, she probably isn't... I don't think she's the type of person who listens to the radio."
  dj "Aww, what's that supposed to mean? Well, you never know! She might remember our show in the same way as you did!"
  dj "Heck, she might even give us a call! Nothing's impossible."
  dj "But okay, I catch your drift. Still, is there any other way you could see yourselves meeting once more?"
  guy "It's kind of stupid, but there might be one way that could end up with meeting us."
  guy "I got a flight back to Bristelline in a few weeks. I postponed it for a long while, but I believe it's best if I get it over with now."
  guy "As it often happens with large corporations, paperwork never ends. I'll have to tie up some loose ends before I can detach myself from them completely."
  guy "So, maybe, if luck will be on our side..."
  guy "We'll manage to meet each other again, in another layover."
  guy "Who says a girl can't miss a plane twice?"
  scene black with Dissolve(2.0)
  return